"use client";

import { GlassPanel } from "@/components/ui";

interface DocumentViewerProps {
    document: any;
}

export default function DocumentViewer({ document }: DocumentViewerProps) {
    // Mocking the document URL/path for display
    // In a real scenario, this would be a link to a blob or PDF

    return (
        <GlassPanel className="overflow-hidden border-white/20 shadow-2xl">
            <div className="bg-slate-950/40 border-b border-white/10 px-6 py-4 flex items-center justify-between">
                <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-lg bg-emerald-500/20 flex items-center justify-center text-emerald-400">
                        {document.type === 'letter' ? '✉️' : '📄'}
                    </div>
                    <div>
                        <h4 className="text-sm font-semibold text-white">{document.title || document.name || "Untitled Vessel"}</h4>
                        <p className="text-[10px] text-white/40 uppercase tracking-widest">{document.type} Layer</p>
                    </div>
                </div>
                <div className="flex items-center gap-2">
                    <button className="p-2 rounded-lg hover:bg-white/5 text-white/40 hover:text-white transition-colors">
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                        </svg>
                    </button>
                    <button className="p-2 rounded-lg hover:bg-white/5 text-white/40 hover:text-white transition-colors">
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                        </svg>
                    </button>
                </div>
            </div>

            <div className="relative h-[65vh] bg-slate-950/20 flex items-center justify-center overflow-hidden">
                {/* Ceremonial Background Elements */}
                <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[150%] h-[150%] bg-gradient-to-br from-emerald-500/5 via-transparent to-sky-500/5 blur-3xl pointer-events-none" />

                {/* The "Vessel" Canvas */}
                <div className="relative z-10 w-full max-w-2xl h-[90%] bg-white shadoow-2xl rounded shadow-[0_0_50px_rgba(0,0,0,0.5)] overflow-y-auto p-12 mx-8">
                    <div className="font-serif text-slate-900 space-y-6">
                        <div className="text-right text-xs text-slate-500 mb-8">
                            Generated by KWANUS OS<br />
                            {new Date().toLocaleDateString()}
                        </div>

                        <div className="space-y-1">
                            <p className="font-bold underline uppercase">Strictly Confidential</p>
                            <p className="text-sm">To: {document.recipient || "Regulatory Bureau"}</p>
                        </div>

                        <h1 className="text-xl font-bold border-b border-slate-200 pb-2">NOTICE OF DISPUTED ACCOUNT</h1>

                        <p className="text-sm leading-relaxed">
                            Dear Representative,
                        </p>

                        <p className="text-sm leading-relaxed">
                            I am writing to formally dispute several items on my credit report. Upon careful review, I have identified inaccurate information regarding the account listed as <strong>{document.accountName || "N/A"}</strong>.
                        </p>

                        <p className="text-sm leading-relaxed">
                            Under the Fair Credit Reporting Act (FCRA), you are required to investigate these claims and verify the accuracy of the information provided by the creditor. If the information cannot be verified, it must be removed or updated immediately.
                        </p>

                        <div className="bg-slate-50 p-4 border border-slate-200 rounded text-xs space-y-2">
                            <p><strong>Creditor:</strong> {document.accountName || "N/A"}</p>
                            <p><strong>Account Number:</strong> {document.accountNumber || "N/A"}</p>
                            <p><strong>Reason for Dispute:</strong> {document.reason || "Inaccurate or incomplete information"}</p>
                        </div>

                        <p className="text-sm leading-relaxed">
                            Please provide a written response regarding the outcome of your investigation within the time frame mandated by federal law.
                        </p>

                        <div className="pt-8">
                            <p className="text-sm">Respectfully,</p>
                            <div className="mt-4 border-b border-slate-300 w-48 h-10 italic text-slate-400 flex items-end pb-1 px-2">
                                Electronic Signature Verified
                            </div>
                            <p className="text-xs text-slate-500 mt-1">Steward Identity Confirmed</p>
                        </div>
                    </div>
                </div>
            </div>

            <div className="bg-slate-950/60 border-t border-white/10 px-6 py-3 flex items-center justify-between">
                <div className="flex items-center gap-4">
                    <div className="px-2 py-0.5 rounded bg-emerald-500/10 text-[9px] font-bold text-emerald-400 uppercase tracking-widest border border-emerald-500/20">
                        Validated
                    </div>
                    <p className="text-[10px] text-white/30 tracking-tight">SHA-256: 8f4e2c...d1a9b3</p>
                </div>
                <p className="text-[10px] text-white/30 italic">Ritual pacing: Harmonious</p>
            </div>
        </GlassPanel>
    );
}
